// Code generated by go-swagger; DO NOT EDIT.

package idle

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new idle API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for idle API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	Postv1idle(params *Postv1idleParams, opts ...ClientOption) (*Postv1idleOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  Postv1idle displays the idle screen on the specified p i n pad

  Use the idle endpoint to return the PIN pad to the idle screen. See <a href='https://triposcert.vantiv.com/api/help/kb/idle.html'>idle documentation</a> for more information.
*/
func (a *Client) Postv1idle(params *Postv1idleParams, opts ...ClientOption) (*Postv1idleOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostv1idleParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "postv1idle",
		Method:             "POST",
		PathPattern:        "/api/v1/idle",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &Postv1idleReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*Postv1idleOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for postv1idle: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
