// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AdjustmentData adjustment data
//
// swagger:model AdjustmentData
type AdjustmentData struct {

	// amount
	Amount Amount `json:"amount,omitempty"`

	// Adjustment code
	Code string `json:"code,omitempty"`

	// detail
	Detail []string `json:"detail"`
}

// Validate validates this adjustment data
func (m *AdjustmentData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AdjustmentData) validateAmount(formats strfmt.Registry) error {
	if swag.IsZero(m.Amount) { // not required
		return nil
	}

	if err := m.Amount.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("amount")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("amount")
		}
		return err
	}

	return nil
}

// ContextValidate validate this adjustment data based on the context it is used
func (m *AdjustmentData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAmount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AdjustmentData) contextValidateAmount(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Amount.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("amount")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("amount")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AdjustmentData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdjustmentData) UnmarshalBinary(b []byte) error {
	var res AdjustmentData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
