// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// CCCvc Credit card verification code
// Example: 432
//
// swagger:model CCCvc
type CCCvc string

// Validate validates this c c cvc
func (m CCCvc) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MinLength("", "body", string(m), 3); err != nil {
		return err
	}

	if err := validate.MaxLength("", "body", string(m), 4); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this c c cvc based on context it is used
func (m CCCvc) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
