// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// DeviceID EFTPOS device ID
// Example: DX01234124-1241240-1231
//
// swagger:model DeviceId
type DeviceID string

// Validate validates this device Id
func (m DeviceID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MaxLength("", "body", string(m), 32); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this device Id based on context it is used
func (m DeviceID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
