// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// DeviceIdleMessage EFTPOS message to display while idle
// Example: Honest John Car Rental
//
// swagger:model DeviceIdleMessage
type DeviceIdleMessage string

// Validate validates this device idle message
func (m DeviceIdleMessage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this device idle message based on context it is used
func (m DeviceIdleMessage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
