// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// DeviceActivationCode Activation code for the EFTPOS device
// Example: X123456
//
// swagger:model DeviceActivationCode
type DeviceActivationCode string

// Validate validates this device activation code
func (m DeviceActivationCode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this device activation code based on context it is used
func (m DeviceActivationCode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
