// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// EventID Transaction event reference (internal)
// Example: 0173c58c-f772-41b8-bdd9-3c150abe2356
//
// swagger:model EventID
type EventID strfmt.UUID

// Validate validates this event ID
func (m EventID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.FormatOf("", "body", "uuid", strfmt.UUID(m).String(), formats); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this event ID based on context it is used
func (m EventID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
