// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Location Location of the client branch of the rental
// Example: GBR-RAC-0123
//
// swagger:model Location
type Location string

// Validate validates this location
func (m Location) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MaxLength("", "body", string(m), 32); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this location based on context it is used
func (m Location) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
