// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// POSID Point of Sale device ID
// Example: TEL-00
//
// swagger:model POSId
type POSID string

// Validate validates this p o s Id
func (m POSID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MaxLength("", "body", string(m), 32); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this p o s Id based on context it is used
func (m POSID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
