// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ReceiptText Receipt text, if this is populated without being Complete then it requires approval
// Example: Thermeon                   Vantage House              Mid Street                                            *---------EFTPOS----------*MERCHANT          123456789TERMINAL           1234567826 Jul 19 14:32            MASTERCARD            SWIPECARD       ************1114AUTHORISATION        002830REFERENCE            000812AUTH              GBP123.45TOTAL             GBP123.45                                   AUTHORISED                                         PLEASE SIGN BELOW                                                                                                                 *-------------------------*       MERCHANT COPY                                         PLEASE RETAIN            FOR YOUR RECORDS
//
// swagger:model ReceiptText
type ReceiptText string

// Validate validates this receipt text
func (m ReceiptText) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this receipt text based on context it is used
func (m ReceiptText) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
