// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new status API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for status API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	Getv1status(params *Getv1statusParams, opts ...ClientOption) (*Getv1statusOK, error)

	Getv1statushost(params *Getv1statushostParams, opts ...ClientOption) (*Getv1statushostOK, error)

	Getv1statustriPOSecho(params *Getv1statustriPOSechoParams, opts ...ClientOption) (*Getv1statustriPOSechoOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  Getv1status returns a list of the tri p o s status endpoints
*/
func (a *Client) Getv1status(params *Getv1statusParams, opts ...ClientOption) (*Getv1statusOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetv1statusParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getv1status",
		Method:             "GET",
		PathPattern:        "/api/v1/status",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &Getv1statusReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*Getv1statusOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getv1status: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Getv1statushost gets host status
*/
func (a *Client) Getv1statushost(params *Getv1statushostParams, opts ...ClientOption) (*Getv1statushostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetv1statushostParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getv1statushost",
		Method:             "GET",
		PathPattern:        "/api/v1/status/host",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &Getv1statushostReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*Getv1statushostOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getv1statushost: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  Getv1statustriPOSecho echos the text passed to tri p o s a successful echo indicates that tri p o s is running and responding to requests
*/
func (a *Client) Getv1statustriPOSecho(params *Getv1statustriPOSechoParams, opts ...ClientOption) (*Getv1statustriPOSechoOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetv1statustriPOSechoParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getv1statustriPOSecho",
		Method:             "GET",
		PathPattern:        "/api/v1/status/triPOS/{echo}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &Getv1statustriPOSechoReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*Getv1statustriPOSechoOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getv1statustriPOSecho: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
