// Code generated by go-swagger; DO NOT EDIT.

package token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/thermeon/boilerplate-golang/infrastructures/clients/tripos/models"
)

// Postv1tokenpaymetricReader is a Reader for the Postv1tokenpaymetric structure.
type Postv1tokenpaymetricReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Postv1tokenpaymetricReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostv1tokenpaymetricOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostv1tokenpaymetricUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostv1tokenpaymetricInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostv1tokenpaymetricOK creates a Postv1tokenpaymetricOK with default headers values
func NewPostv1tokenpaymetricOK() *Postv1tokenpaymetricOK {
	return &Postv1tokenpaymetricOK{}
}

/* Postv1tokenpaymetricOK describes a response with status code 200, with default header values.

Success
*/
type Postv1tokenpaymetricOK struct {
	Payload *models.CreatePaymetricTokenResponse
}

func (o *Postv1tokenpaymetricOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/token/paymetric][%d] postv1tokenpaymetricOK  %+v", 200, o.Payload)
}
func (o *Postv1tokenpaymetricOK) GetPayload() *models.CreatePaymetricTokenResponse {
	return o.Payload
}

func (o *Postv1tokenpaymetricOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreatePaymetricTokenResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostv1tokenpaymetricUnauthorized creates a Postv1tokenpaymetricUnauthorized with default headers values
func NewPostv1tokenpaymetricUnauthorized() *Postv1tokenpaymetricUnauthorized {
	return &Postv1tokenpaymetricUnauthorized{}
}

/* Postv1tokenpaymetricUnauthorized describes a response with status code 401, with default header values.

Returned if the AcceptorId, AccountId, AccountToken and TerminalId (config file only) are not provided in the HTTP request header or in the config file.
*/
type Postv1tokenpaymetricUnauthorized struct {
}

func (o *Postv1tokenpaymetricUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1/token/paymetric][%d] postv1tokenpaymetricUnauthorized ", 401)
}

func (o *Postv1tokenpaymetricUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostv1tokenpaymetricInternalServerError creates a Postv1tokenpaymetricInternalServerError with default headers values
func NewPostv1tokenpaymetricInternalServerError() *Postv1tokenpaymetricInternalServerError {
	return &Postv1tokenpaymetricInternalServerError{}
}

/* Postv1tokenpaymetricInternalServerError describes a response with status code 500, with default header values.

The token could not be created with the card used.
*/
type Postv1tokenpaymetricInternalServerError struct {
}

func (o *Postv1tokenpaymetricInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/token/paymetric][%d] postv1tokenpaymetricInternalServerError ", 500)
}

func (o *Postv1tokenpaymetricInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
