// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetLanesHandlerFunc turns a function with the right signature into a get lanes handler
type GetLanesHandlerFunc func(GetLanesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLanesHandlerFunc) Handle(params GetLanesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetLanesHandler interface for that can handle valid get lanes params
type GetLanesHandler interface {
	Handle(GetLanesParams, interface{}) middleware.Responder
}

// NewGetLanes creates a new http.Handler for the get lanes operation
func NewGetLanes(ctx *middleware.Context, handler GetLanesHandler) *GetLanes {
	return &GetLanes{Context: ctx, Handler: handler}
}

/* GetLanes swagger:route GET /lanes/{processor}/{location} getLanes

Retrieve collection of all configured lanes

*/
type GetLanes struct {
	Context *middleware.Context
	Handler GetLanesHandler
}

func (o *GetLanes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetLanesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
