// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/thermeon/boilerplate-golang/infrastructures/server/models"
)

// RetrieveTransactionHistoryOKCode is the HTTP code returned for type RetrieveTransactionHistoryOK
const RetrieveTransactionHistoryOKCode int = 200

/*RetrieveTransactionHistoryOK Transaction found and retrieved

swagger:response retrieveTransactionHistoryOK
*/
type RetrieveTransactionHistoryOK struct {

	/*
	  In: Body
	*/
	Payload *models.TransactionHistory `json:"body,omitempty"`
}

// NewRetrieveTransactionHistoryOK creates RetrieveTransactionHistoryOK with default headers values
func NewRetrieveTransactionHistoryOK() *RetrieveTransactionHistoryOK {

	return &RetrieveTransactionHistoryOK{}
}

// WithPayload adds the payload to the retrieve transaction history o k response
func (o *RetrieveTransactionHistoryOK) WithPayload(payload *models.TransactionHistory) *RetrieveTransactionHistoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve transaction history o k response
func (o *RetrieveTransactionHistoryOK) SetPayload(payload *models.TransactionHistory) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveTransactionHistoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RetrieveTransactionHistoryBadRequestCode is the HTTP code returned for type RetrieveTransactionHistoryBadRequest
const RetrieveTransactionHistoryBadRequestCode int = 400

/*RetrieveTransactionHistoryBadRequest Bad Request

swagger:response retrieveTransactionHistoryBadRequest
*/
type RetrieveTransactionHistoryBadRequest struct {
}

// NewRetrieveTransactionHistoryBadRequest creates RetrieveTransactionHistoryBadRequest with default headers values
func NewRetrieveTransactionHistoryBadRequest() *RetrieveTransactionHistoryBadRequest {

	return &RetrieveTransactionHistoryBadRequest{}
}

// WriteResponse to the client
func (o *RetrieveTransactionHistoryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// RetrieveTransactionHistoryUnauthorizedCode is the HTTP code returned for type RetrieveTransactionHistoryUnauthorized
const RetrieveTransactionHistoryUnauthorizedCode int = 401

/*RetrieveTransactionHistoryUnauthorized Unauthorized

swagger:response retrieveTransactionHistoryUnauthorized
*/
type RetrieveTransactionHistoryUnauthorized struct {
}

// NewRetrieveTransactionHistoryUnauthorized creates RetrieveTransactionHistoryUnauthorized with default headers values
func NewRetrieveTransactionHistoryUnauthorized() *RetrieveTransactionHistoryUnauthorized {

	return &RetrieveTransactionHistoryUnauthorized{}
}

// WriteResponse to the client
func (o *RetrieveTransactionHistoryUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// RetrieveTransactionHistoryNotFoundCode is the HTTP code returned for type RetrieveTransactionHistoryNotFound
const RetrieveTransactionHistoryNotFoundCode int = 404

/*RetrieveTransactionHistoryNotFound Not Found

swagger:response retrieveTransactionHistoryNotFound
*/
type RetrieveTransactionHistoryNotFound struct {
}

// NewRetrieveTransactionHistoryNotFound creates RetrieveTransactionHistoryNotFound with default headers values
func NewRetrieveTransactionHistoryNotFound() *RetrieveTransactionHistoryNotFound {

	return &RetrieveTransactionHistoryNotFound{}
}

// WriteResponse to the client
func (o *RetrieveTransactionHistoryNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*RetrieveTransactionHistoryDefault generic error response

swagger:response retrieveTransactionHistoryDefault
*/
type RetrieveTransactionHistoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRetrieveTransactionHistoryDefault creates RetrieveTransactionHistoryDefault with default headers values
func NewRetrieveTransactionHistoryDefault(code int) *RetrieveTransactionHistoryDefault {
	if code <= 0 {
		code = 500
	}

	return &RetrieveTransactionHistoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the retrieve transaction history default response
func (o *RetrieveTransactionHistoryDefault) WithStatusCode(code int) *RetrieveTransactionHistoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the retrieve transaction history default response
func (o *RetrieveTransactionHistoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the retrieve transaction history default response
func (o *RetrieveTransactionHistoryDefault) WithPayload(payload *models.Error) *RetrieveTransactionHistoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the retrieve transaction history default response
func (o *RetrieveTransactionHistoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RetrieveTransactionHistoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
