// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SaleTransactionHandlerFunc turns a function with the right signature into a sale transaction handler
type SaleTransactionHandlerFunc func(SaleTransactionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SaleTransactionHandlerFunc) Handle(params SaleTransactionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SaleTransactionHandler interface for that can handle valid sale transaction params
type SaleTransactionHandler interface {
	Handle(SaleTransactionParams, interface{}) middleware.Responder
}

// NewSaleTransaction creates a new http.Handler for the sale transaction operation
func NewSaleTransaction(ctx *middleware.Context, handler SaleTransactionHandler) *SaleTransaction {
	return &SaleTransaction{Context: ctx, Handler: handler}
}

/* SaleTransaction swagger:route POST /transaction/sale saleTransaction

AUTH and CAPTURE in a single operation

*/
type SaleTransaction struct {
	Context *middleware.Context
	Handler SaleTransactionHandler
}

func (o *SaleTransaction) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSaleTransactionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
