// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/thermeon/boilerplate-golang/infrastructures/server/models"
)

// NewTokenizeCardParams creates a new TokenizeCardParams object
//
// There are no default values defined in the spec.
func NewTokenizeCardParams() TokenizeCardParams {

	return TokenizeCardParams{}
}

// TokenizeCardParams contains all the bound params for the tokenize card operation
// typically these are obtained from a http.Request
//
// swagger:parameters TokenizeCard
type TokenizeCardParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	RequestTokenize *models.Tokenize
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewTokenizeCardParams() beforehand.
func (o *TokenizeCardParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Tokenize
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("requestTokenize", "body", ""))
			} else {
				res = append(res, errors.NewParseError("requestTokenize", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.RequestTokenize = &body
			}
		}
	} else {
		res = append(res, errors.Required("requestTokenize", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
