// Code generated by go-swagger; DO NOT EDIT.

package pinpad

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/thermeon/boilerplate-golang/infrastructures/clients/tripos/models"
)

// Getv1pinpadcardfinanciallaneIDReader is a Reader for the Getv1pinpadcardfinanciallaneID structure.
type Getv1pinpadcardfinanciallaneIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Getv1pinpadcardfinanciallaneIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetv1pinpadcardfinanciallaneIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetv1pinpadcardfinanciallaneIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetv1pinpadcardfinanciallaneIDOK creates a Getv1pinpadcardfinanciallaneIDOK with default headers values
func NewGetv1pinpadcardfinanciallaneIDOK() *Getv1pinpadcardfinanciallaneIDOK {
	return &Getv1pinpadcardfinanciallaneIDOK{}
}

/* Getv1pinpadcardfinanciallaneIDOK describes a response with status code 200, with default header values.

Success
*/
type Getv1pinpadcardfinanciallaneIDOK struct {
	Payload *models.FinancialCardResponse
}

func (o *Getv1pinpadcardfinanciallaneIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/pinpad/card/financial/{laneId}][%d] getv1pinpadcardfinanciallaneIdOK  %+v", 200, o.Payload)
}
func (o *Getv1pinpadcardfinanciallaneIDOK) GetPayload() *models.FinancialCardResponse {
	return o.Payload
}

func (o *Getv1pinpadcardfinanciallaneIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FinancialCardResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetv1pinpadcardfinanciallaneIDNotFound creates a Getv1pinpadcardfinanciallaneIDNotFound with default headers values
func NewGetv1pinpadcardfinanciallaneIDNotFound() *Getv1pinpadcardfinanciallaneIDNotFound {
	return &Getv1pinpadcardfinanciallaneIDNotFound{}
}

/* Getv1pinpadcardfinanciallaneIDNotFound describes a response with status code 404, with default header values.

Returned if no financial data can be found when the card is swiped.
*/
type Getv1pinpadcardfinanciallaneIDNotFound struct {
}

func (o *Getv1pinpadcardfinanciallaneIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/pinpad/card/financial/{laneId}][%d] getv1pinpadcardfinanciallaneIdNotFound ", 404)
}

func (o *Getv1pinpadcardfinanciallaneIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
