// Code generated by go-swagger; DO NOT EDIT.

package v1_links

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/thermeon/boilerplate-golang/infrastructures/clients/tripos/models"
)

// Getv1Reader is a Reader for the Getv1 structure.
type Getv1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Getv1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetv1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetv1OK creates a Getv1OK with default headers values
func NewGetv1OK() *Getv1OK {
	return &Getv1OK{}
}

/* Getv1OK describes a response with status code 200, with default header values.

Success
*/
type Getv1OK struct {
	Payload *models.GetServicesResponse
}

func (o *Getv1OK) Error() string {
	return fmt.Sprintf("[GET /api/v1][%d] getv1OK  %+v", 200, o.Payload)
}
func (o *Getv1OK) GetPayload() *models.GetServicesResponse {
	return o.Payload
}

func (o *Getv1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetServicesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
