// Code generated by go-swagger; DO NOT EDIT.

package bin_query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/thermeon/boilerplate-golang/infrastructures/clients/tripos/models"
)

// Getv1binQuerylaneIDReader is a Reader for the Getv1binQuerylaneID structure.
type Getv1binQuerylaneIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Getv1binQuerylaneIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetv1binQuerylaneIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetv1binQuerylaneIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetv1binQuerylaneIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetv1binQuerylaneIDOK creates a Getv1binQuerylaneIDOK with default headers values
func NewGetv1binQuerylaneIDOK() *Getv1binQuerylaneIDOK {
	return &Getv1binQuerylaneIDOK{}
}

/* Getv1binQuerylaneIDOK describes a response with status code 200, with default header values.

Success
*/
type Getv1binQuerylaneIDOK struct {
	Payload *models.BinQueryResponse
}

func (o *Getv1binQuerylaneIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/binQuery/{laneId}][%d] getv1binQuerylaneIdOK  %+v", 200, o.Payload)
}
func (o *Getv1binQuerylaneIDOK) GetPayload() *models.BinQueryResponse {
	return o.Payload
}

func (o *Getv1binQuerylaneIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BinQueryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetv1binQuerylaneIDUnauthorized creates a Getv1binQuerylaneIDUnauthorized with default headers values
func NewGetv1binQuerylaneIDUnauthorized() *Getv1binQuerylaneIDUnauthorized {
	return &Getv1binQuerylaneIDUnauthorized{}
}

/* Getv1binQuerylaneIDUnauthorized describes a response with status code 401, with default header values.

Returned if the AcceptorId, AccountId, AccountToken and TerminalId (config file only) are not provided in the HTTP request header or in the config file.
*/
type Getv1binQuerylaneIDUnauthorized struct {
}

func (o *Getv1binQuerylaneIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/binQuery/{laneId}][%d] getv1binQuerylaneIdUnauthorized ", 401)
}

func (o *Getv1binQuerylaneIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetv1binQuerylaneIDNotFound creates a Getv1binQuerylaneIDNotFound with default headers values
func NewGetv1binQuerylaneIDNotFound() *Getv1binQuerylaneIDNotFound {
	return &Getv1binQuerylaneIDNotFound{}
}

/* Getv1binQuerylaneIDNotFound describes a response with status code 404, with default header values.

Returned if card is not found in the BIN table
*/
type Getv1binQuerylaneIDNotFound struct {
}

func (o *Getv1binQuerylaneIDNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/binQuery/{laneId}][%d] getv1binQuerylaneIdNotFound ", 404)
}

func (o *Getv1binQuerylaneIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
