// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProfileDto profile dto
//
// swagger:model ProfileDto
type ProfileDto struct {

	// idle message
	IdleMessage string `json:"idleMessage,omitempty"`
}

// Validate validates this profile dto
func (m *ProfileDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this profile dto based on context it is used
func (m *ProfileDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProfileDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProfileDto) UnmarshalBinary(b []byte) error {
	var res ProfileDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
