// Code generated by go-swagger; DO NOT EDIT.

package payment_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/thermeon/boilerplate-golang/infrastructures/clients/tripos/models"
)

// NewDeletev1paymentAccountpaymentAccountIDParams creates a new Deletev1paymentAccountpaymentAccountIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeletev1paymentAccountpaymentAccountIDParams() *Deletev1paymentAccountpaymentAccountIDParams {
	return &Deletev1paymentAccountpaymentAccountIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeletev1paymentAccountpaymentAccountIDParamsWithTimeout creates a new Deletev1paymentAccountpaymentAccountIDParams object
// with the ability to set a timeout on a request.
func NewDeletev1paymentAccountpaymentAccountIDParamsWithTimeout(timeout time.Duration) *Deletev1paymentAccountpaymentAccountIDParams {
	return &Deletev1paymentAccountpaymentAccountIDParams{
		timeout: timeout,
	}
}

// NewDeletev1paymentAccountpaymentAccountIDParamsWithContext creates a new Deletev1paymentAccountpaymentAccountIDParams object
// with the ability to set a context for a request.
func NewDeletev1paymentAccountpaymentAccountIDParamsWithContext(ctx context.Context) *Deletev1paymentAccountpaymentAccountIDParams {
	return &Deletev1paymentAccountpaymentAccountIDParams{
		Context: ctx,
	}
}

// NewDeletev1paymentAccountpaymentAccountIDParamsWithHTTPClient creates a new Deletev1paymentAccountpaymentAccountIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeletev1paymentAccountpaymentAccountIDParamsWithHTTPClient(client *http.Client) *Deletev1paymentAccountpaymentAccountIDParams {
	return &Deletev1paymentAccountpaymentAccountIDParams{
		HTTPClient: client,
	}
}

/* Deletev1paymentAccountpaymentAccountIDParams contains all the parameters to send to the API endpoint
   for the deletev1payment accountpayment account Id operation.

   Typically these are written to a http.Request.
*/
type Deletev1paymentAccountpaymentAccountIDParams struct {

	/* ContentType.

	   Content type for request.

	   Default: "application/json"
	*/
	ContentType string

	// DeletePaymentAccountRequest.
	DeletePaymentAccountRequest *models.DELETEDeletePaymentAccountRequestV1PaymentAccountPaymentAccountID

	/* PaymentAccountID.

	   The payment account ID to update.
	*/
	PaymentAccountID string

	/* TpApplicationID.

	   The ID of the business application.
	*/
	TpApplicationID string

	/* TpApplicationName.

	   The name of the business application.
	*/
	TpApplicationName string

	/* TpApplicationVersion.

	   The version of the business application.
	*/
	TpApplicationVersion string

	/* TpAuthorization.

	   The authorization header.
	*/
	TpAuthorization string

	/* TpExpressAcceptorID.

	   The Express acceptorId. If all three Express credentials are specified in the request headers, triPOS will use these credentials instead of the credentials in the triPOS.config for that request only.
	*/
	TpExpressAcceptorID string

	/* TpExpressAccountID.

	   The Express accountId. If all three Express credentials are specified in the request headers, triPOS will use these credentials instead of the credentials in the triPOS.config for that request only.
	*/
	TpExpressAccountID string

	/* TpExpressAccountToken.

	   The Express accountToken. If all three Express credentials are specified in the request headers, triPOS will use these credentials instead of the credentials in the triPOS.config for that request only.
	*/
	TpExpressAccountToken string

	/* TpRequestID.

	   A unique ID for this request. This value should be a UUID or GUID. <a href='https://triposcert.vantiv.com/api/help/kb/requestid.html'>more&raquo;</a>
	*/
	TpRequestID string

	/* TpReturnLogs.

	   Set to true to have logs populated in the response.
	*/
	TpReturnLogs *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the deletev1payment accountpayment account Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithDefaults() *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the deletev1payment accountpayment account Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetDefaults() {
	var (
		contentTypeDefault = string("application/json")
	)

	val := Deletev1paymentAccountpaymentAccountIDParams{
		ContentType: contentTypeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithTimeout(timeout time.Duration) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithContext(ctx context.Context) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithHTTPClient(client *http.Client) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithContentType(contentType string) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithDeletePaymentAccountRequest adds the deletePaymentAccountRequest to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithDeletePaymentAccountRequest(deletePaymentAccountRequest *models.DELETEDeletePaymentAccountRequestV1PaymentAccountPaymentAccountID) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetDeletePaymentAccountRequest(deletePaymentAccountRequest)
	return o
}

// SetDeletePaymentAccountRequest adds the deletePaymentAccountRequest to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetDeletePaymentAccountRequest(deletePaymentAccountRequest *models.DELETEDeletePaymentAccountRequestV1PaymentAccountPaymentAccountID) {
	o.DeletePaymentAccountRequest = deletePaymentAccountRequest
}

// WithPaymentAccountID adds the paymentAccountID to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithPaymentAccountID(paymentAccountID string) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetPaymentAccountID(paymentAccountID)
	return o
}

// SetPaymentAccountID adds the paymentAccountId to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetPaymentAccountID(paymentAccountID string) {
	o.PaymentAccountID = paymentAccountID
}

// WithTpApplicationID adds the tpApplicationID to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithTpApplicationID(tpApplicationID string) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetTpApplicationID(tpApplicationID)
	return o
}

// SetTpApplicationID adds the tpApplicationId to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetTpApplicationID(tpApplicationID string) {
	o.TpApplicationID = tpApplicationID
}

// WithTpApplicationName adds the tpApplicationName to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithTpApplicationName(tpApplicationName string) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetTpApplicationName(tpApplicationName)
	return o
}

// SetTpApplicationName adds the tpApplicationName to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetTpApplicationName(tpApplicationName string) {
	o.TpApplicationName = tpApplicationName
}

// WithTpApplicationVersion adds the tpApplicationVersion to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithTpApplicationVersion(tpApplicationVersion string) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetTpApplicationVersion(tpApplicationVersion)
	return o
}

// SetTpApplicationVersion adds the tpApplicationVersion to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetTpApplicationVersion(tpApplicationVersion string) {
	o.TpApplicationVersion = tpApplicationVersion
}

// WithTpAuthorization adds the tpAuthorization to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithTpAuthorization(tpAuthorization string) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetTpAuthorization(tpAuthorization)
	return o
}

// SetTpAuthorization adds the tpAuthorization to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetTpAuthorization(tpAuthorization string) {
	o.TpAuthorization = tpAuthorization
}

// WithTpExpressAcceptorID adds the tpExpressAcceptorID to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithTpExpressAcceptorID(tpExpressAcceptorID string) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetTpExpressAcceptorID(tpExpressAcceptorID)
	return o
}

// SetTpExpressAcceptorID adds the tpExpressAcceptorId to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetTpExpressAcceptorID(tpExpressAcceptorID string) {
	o.TpExpressAcceptorID = tpExpressAcceptorID
}

// WithTpExpressAccountID adds the tpExpressAccountID to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithTpExpressAccountID(tpExpressAccountID string) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetTpExpressAccountID(tpExpressAccountID)
	return o
}

// SetTpExpressAccountID adds the tpExpressAccountId to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetTpExpressAccountID(tpExpressAccountID string) {
	o.TpExpressAccountID = tpExpressAccountID
}

// WithTpExpressAccountToken adds the tpExpressAccountToken to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithTpExpressAccountToken(tpExpressAccountToken string) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetTpExpressAccountToken(tpExpressAccountToken)
	return o
}

// SetTpExpressAccountToken adds the tpExpressAccountToken to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetTpExpressAccountToken(tpExpressAccountToken string) {
	o.TpExpressAccountToken = tpExpressAccountToken
}

// WithTpRequestID adds the tpRequestID to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithTpRequestID(tpRequestID string) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetTpRequestID(tpRequestID)
	return o
}

// SetTpRequestID adds the tpRequestId to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetTpRequestID(tpRequestID string) {
	o.TpRequestID = tpRequestID
}

// WithTpReturnLogs adds the tpReturnLogs to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) WithTpReturnLogs(tpReturnLogs *bool) *Deletev1paymentAccountpaymentAccountIDParams {
	o.SetTpReturnLogs(tpReturnLogs)
	return o
}

// SetTpReturnLogs adds the tpReturnLogs to the deletev1payment accountpayment account Id params
func (o *Deletev1paymentAccountpaymentAccountIDParams) SetTpReturnLogs(tpReturnLogs *bool) {
	o.TpReturnLogs = tpReturnLogs
}

// WriteToRequest writes these params to a swagger request
func (o *Deletev1paymentAccountpaymentAccountIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}
	if o.DeletePaymentAccountRequest != nil {
		if err := r.SetBodyParam(o.DeletePaymentAccountRequest); err != nil {
			return err
		}
	}

	// path param paymentAccountId
	if err := r.SetPathParam("paymentAccountId", o.PaymentAccountID); err != nil {
		return err
	}

	// header param tp-application-id
	if err := r.SetHeaderParam("tp-application-id", o.TpApplicationID); err != nil {
		return err
	}

	// header param tp-application-name
	if err := r.SetHeaderParam("tp-application-name", o.TpApplicationName); err != nil {
		return err
	}

	// header param tp-application-version
	if err := r.SetHeaderParam("tp-application-version", o.TpApplicationVersion); err != nil {
		return err
	}

	// header param tp-authorization
	if err := r.SetHeaderParam("tp-authorization", o.TpAuthorization); err != nil {
		return err
	}

	// header param tp-express-acceptor-id
	if err := r.SetHeaderParam("tp-express-acceptor-id", o.TpExpressAcceptorID); err != nil {
		return err
	}

	// header param tp-express-account-id
	if err := r.SetHeaderParam("tp-express-account-id", o.TpExpressAccountID); err != nil {
		return err
	}

	// header param tp-express-account-token
	if err := r.SetHeaderParam("tp-express-account-token", o.TpExpressAccountToken); err != nil {
		return err
	}

	// header param tp-request-id
	if err := r.SetHeaderParam("tp-request-id", o.TpRequestID); err != nil {
		return err
	}

	if o.TpReturnLogs != nil {

		// header param tp-return-logs
		if err := r.SetHeaderParam("tp-return-logs", swag.FormatBool(*o.TpReturnLogs)); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
