// Code generated by go-swagger; DO NOT EDIT.

package payment_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/thermeon/boilerplate-golang/infrastructures/clients/tripos/models"
)

// Postv1paymentAccountcreditReader is a Reader for the Postv1paymentAccountcredit structure.
type Postv1paymentAccountcreditReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Postv1paymentAccountcreditReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostv1paymentAccountcreditOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostv1paymentAccountcreditUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostv1paymentAccountcreditOK creates a Postv1paymentAccountcreditOK with default headers values
func NewPostv1paymentAccountcreditOK() *Postv1paymentAccountcreditOK {
	return &Postv1paymentAccountcreditOK{}
}

/* Postv1paymentAccountcreditOK describes a response with status code 200, with default header values.

Success
*/
type Postv1paymentAccountcreditOK struct {
	Payload *models.CreatePaymentAccountCreditResponse
}

func (o *Postv1paymentAccountcreditOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/paymentAccount/credit][%d] postv1paymentAccountcreditOK  %+v", 200, o.Payload)
}
func (o *Postv1paymentAccountcreditOK) GetPayload() *models.CreatePaymentAccountCreditResponse {
	return o.Payload
}

func (o *Postv1paymentAccountcreditOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreatePaymentAccountCreditResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostv1paymentAccountcreditUnauthorized creates a Postv1paymentAccountcreditUnauthorized with default headers values
func NewPostv1paymentAccountcreditUnauthorized() *Postv1paymentAccountcreditUnauthorized {
	return &Postv1paymentAccountcreditUnauthorized{}
}

/* Postv1paymentAccountcreditUnauthorized describes a response with status code 401, with default header values.

Returned if the AcceptorId, AccountId, AccountToken and TerminalId (config file only) are not provided in the HTTP request header or in the config file.
*/
type Postv1paymentAccountcreditUnauthorized struct {
}

func (o *Postv1paymentAccountcreditUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1/paymentAccount/credit][%d] postv1paymentAccountcreditUnauthorized ", 401)
}

func (o *Postv1paymentAccountcreditUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
