// Code generated by go-swagger; DO NOT EDIT.

package reboot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/thermeon/boilerplate-golang/infrastructures/clients/tripos/models"
)

// Postv1rebootReader is a Reader for the Postv1reboot structure.
type Postv1rebootReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Postv1rebootReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostv1rebootOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostv1rebootBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostv1rebootNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostv1rebootInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostv1rebootOK creates a Postv1rebootOK with default headers values
func NewPostv1rebootOK() *Postv1rebootOK {
	return &Postv1rebootOK{}
}

/* Postv1rebootOK describes a response with status code 200, with default header values.

Success
*/
type Postv1rebootOK struct {
	Payload *models.RebootLaneResponse
}

func (o *Postv1rebootOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/reboot][%d] postv1rebootOK  %+v", 200, o.Payload)
}
func (o *Postv1rebootOK) GetPayload() *models.RebootLaneResponse {
	return o.Payload
}

func (o *Postv1rebootOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RebootLaneResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostv1rebootBadRequest creates a Postv1rebootBadRequest with default headers values
func NewPostv1rebootBadRequest() *Postv1rebootBadRequest {
	return &Postv1rebootBadRequest{}
}

/* Postv1rebootBadRequest describes a response with status code 400, with default header values.

Returned if the laneId is null or 0
*/
type Postv1rebootBadRequest struct {
}

func (o *Postv1rebootBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v1/reboot][%d] postv1rebootBadRequest ", 400)
}

func (o *Postv1rebootBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostv1rebootNotFound creates a Postv1rebootNotFound with default headers values
func NewPostv1rebootNotFound() *Postv1rebootNotFound {
	return &Postv1rebootNotFound{}
}

/* Postv1rebootNotFound describes a response with status code 404, with default header values.

Returned if the laneId is not valid
*/
type Postv1rebootNotFound struct {
}

func (o *Postv1rebootNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v1/reboot][%d] postv1rebootNotFound ", 404)
}

func (o *Postv1rebootNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostv1rebootInternalServerError creates a Postv1rebootInternalServerError with default headers values
func NewPostv1rebootInternalServerError() *Postv1rebootInternalServerError {
	return &Postv1rebootInternalServerError{}
}

/* Postv1rebootInternalServerError describes a response with status code 500, with default header values.

Returned if the PIN pad is disconnected or lane is already in use
*/
type Postv1rebootInternalServerError struct {
}

func (o *Postv1rebootInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/reboot][%d] postv1rebootInternalServerError ", 500)
}

func (o *Postv1rebootInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
