// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AutoRentalBasic AutoRentalBasic
//
// swagger:model AutoRentalBasic
type AutoRentalBasic struct {

	// The number of rental days. Value should be between 0 and 99. Set to 01 for no show rentals.
	Duration int32 `json:"duration,omitempty"`
}

// Validate validates this auto rental basic
func (m *AutoRentalBasic) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auto rental basic based on context it is used
func (m *AutoRentalBasic) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AutoRentalBasic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AutoRentalBasic) UnmarshalBinary(b []byte) error {
	var res AutoRentalBasic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
