// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EmvTagKeyValue EmvTagKeyValue
//
// swagger:model EmvTagKeyValue
type EmvTagKeyValue struct {

	// key
	Key string `json:"key,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this emv tag key value
func (m *EmvTagKeyValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this emv tag key value based on context it is used
func (m *EmvTagKeyValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EmvTagKeyValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EmvTagKeyValue) UnmarshalBinary(b []byte) error {
	var res EmvTagKeyValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
