// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GETILaneLockV1StatusHost ILaneLock
//
// swagger:model GET_ILaneLock_v1_status_host
type GETILaneLockV1StatusHost struct {

	// id
	// Required: true
	ID GETGUIDV1StatusHost `json:"id"`
}

// Validate validates this g e t i lane lock v1 status host
func (m *GETILaneLockV1StatusHost) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GETILaneLockV1StatusHost) validateID(formats strfmt.Registry) error {

	if m.ID == nil {
		return errors.Required("id", "body", nil)
	}

	return nil
}

// ContextValidate validates this g e t i lane lock v1 status host based on context it is used
func (m *GETILaneLockV1StatusHost) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GETILaneLockV1StatusHost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GETILaneLockV1StatusHost) UnmarshalBinary(b []byte) error {
	var res GETILaneLockV1StatusHost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
