// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GETFinancialCardRequestV1CardFinancialLaneID FinancialCardRequest
//
// swagger:model GET_FinancialCardRequest_v1_card_financial_laneId
type GETFinancialCardRequestV1CardFinancialLaneID struct {

	// The flag that invokes manual entry directly.
	InvokeManualEntry bool `json:"invokeManualEntry,omitempty"`
}

// Validate validates this g e t financial card request v1 card financial lane Id
func (m *GETFinancialCardRequestV1CardFinancialLaneID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this g e t financial card request v1 card financial lane Id based on context it is used
func (m *GETFinancialCardRequestV1CardFinancialLaneID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GETFinancialCardRequestV1CardFinancialLaneID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GETFinancialCardRequestV1CardFinancialLaneID) UnmarshalBinary(b []byte) error {
	var res GETFinancialCardRequestV1CardFinancialLaneID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
