// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GETNonFinancialCardRequestV1CardNonfinancialLaneID NonFinancialCardRequest
//
// swagger:model GET_NonFinancialCardRequest_v1_card_nonfinancial_laneId
type GETNonFinancialCardRequestV1CardNonfinancialLaneID struct {

	// The flag that invokes manual entry directly.
	InvokeManualEntry bool `json:"invokeManualEntry,omitempty"`
}

// Validate validates this g e t non financial card request v1 card nonfinancial lane Id
func (m *GETNonFinancialCardRequestV1CardNonfinancialLaneID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this g e t non financial card request v1 card nonfinancial lane Id based on context it is used
func (m *GETNonFinancialCardRequestV1CardNonfinancialLaneID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GETNonFinancialCardRequestV1CardNonfinancialLaneID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GETNonFinancialCardRequestV1CardNonfinancialLaneID) UnmarshalBinary(b []byte) error {
	var res GETNonFinancialCardRequestV1CardNonfinancialLaneID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
