// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// POSTAutoRentalReturnDataV1Sale AutoRentalReturnData
//
// swagger:model POST_AutoRentalReturnData_v1_sale
type POSTAutoRentalReturnDataV1Sale struct {

	// Auto rental return city.
	City string `json:"city,omitempty"`

	// Country code where vehicle was returned. For US, use 840.
	CountryCode string `json:"countryCode,omitempty"`

	// return date in yyyy-MM-ddTHH:mm:ss format.
	Date string `json:"date,omitempty"`

	// Numeric distance traveled during rental period.
	Distance int32 `json:"distance,omitempty"`

	// Unit of measurement applicable to distance traveled.
	DistanceUnit string `json:"distanceUnit,omitempty"`

	// Auto Rental location ID where vehicle was returned.
	LocationID string `json:"locationId,omitempty"`

	// Auto rental return state.
	State string `json:"state,omitempty"`
}

// Validate validates this p o s t auto rental return data v1 sale
func (m *POSTAutoRentalReturnDataV1Sale) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this p o s t auto rental return data v1 sale based on context it is used
func (m *POSTAutoRentalReturnDataV1Sale) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *POSTAutoRentalReturnDataV1Sale) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *POSTAutoRentalReturnDataV1Sale) UnmarshalBinary(b []byte) error {
	var res POSTAutoRentalReturnDataV1Sale
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
