// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// POSTIdleRequestV1Idle IdleRequest
//
// swagger:model POST_IdleRequest_v1_idle
type POSTIdleRequestV1Idle struct {

	// Specifies which lane to use.
	// Required: true
	LaneID *int32 `json:"laneId"`
}

// Validate validates this p o s t idle request v1 idle
func (m *POSTIdleRequestV1Idle) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLaneID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *POSTIdleRequestV1Idle) validateLaneID(formats strfmt.Registry) error {

	if err := validate.Required("laneId", "body", m.LaneID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this p o s t idle request v1 idle based on context it is used
func (m *POSTIdleRequestV1Idle) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *POSTIdleRequestV1Idle) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *POSTIdleRequestV1Idle) UnmarshalBinary(b []byte) error {
	var res POSTIdleRequestV1Idle
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
