// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StoreCard StoreCard
//
// swagger:model StoreCard
type StoreCard struct {

	// The ID of a StoreCard.
	ID string `json:"Id,omitempty"`

	// The password of StoreCard.
	Password string `json:"Password,omitempty"`
}

// Validate validates this store card
func (m *StoreCard) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this store card based on context it is used
func (m *StoreCard) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StoreCard) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StoreCard) UnmarshalBinary(b []byte) error {
	var res StoreCard
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
