// Code generated by go-swagger; DO NOT EDIT.

package gift

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/thermeon/boilerplate-golang/infrastructures/clients/tripos/models"
)

// Postv1giftactivateReader is a Reader for the Postv1giftactivate structure.
type Postv1giftactivateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Postv1giftactivateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostv1giftactivateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostv1giftactivateOK creates a Postv1giftactivateOK with default headers values
func NewPostv1giftactivateOK() *Postv1giftactivateOK {
	return &Postv1giftactivateOK{}
}

/* Postv1giftactivateOK describes a response with status code 200, with default header values.

Success
*/
type Postv1giftactivateOK struct {
	Payload *models.ActivateGiftResponse
}

func (o *Postv1giftactivateOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/gift/activate][%d] postv1giftactivateOK  %+v", 200, o.Payload)
}
func (o *Postv1giftactivateOK) GetPayload() *models.ActivateGiftResponse {
	return o.Payload
}

func (o *Postv1giftactivateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ActivateGiftResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
