// Code generated by go-swagger; DO NOT EDIT.

package signature

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetv1signatureParams creates a new Getv1signatureParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetv1signatureParams() *Getv1signatureParams {
	return &Getv1signatureParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetv1signatureParamsWithTimeout creates a new Getv1signatureParams object
// with the ability to set a timeout on a request.
func NewGetv1signatureParamsWithTimeout(timeout time.Duration) *Getv1signatureParams {
	return &Getv1signatureParams{
		timeout: timeout,
	}
}

// NewGetv1signatureParamsWithContext creates a new Getv1signatureParams object
// with the ability to set a context for a request.
func NewGetv1signatureParamsWithContext(ctx context.Context) *Getv1signatureParams {
	return &Getv1signatureParams{
		Context: ctx,
	}
}

// NewGetv1signatureParamsWithHTTPClient creates a new Getv1signatureParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetv1signatureParamsWithHTTPClient(client *http.Client) *Getv1signatureParams {
	return &Getv1signatureParams{
		HTTPClient: client,
	}
}

/* Getv1signatureParams contains all the parameters to send to the API endpoint
   for the getv1signature operation.

   Typically these are written to a http.Request.
*/
type Getv1signatureParams struct {

	/* ContentType.

	   Content type for request.

	   Default: "application/json"
	*/
	ContentType string

	/* TpApplicationID.

	   The ID of the business application.
	*/
	TpApplicationID string

	/* TpApplicationName.

	   The name of the business application.
	*/
	TpApplicationName string

	/* TpApplicationVersion.

	   The version of the business application.
	*/
	TpApplicationVersion string

	/* TpAuthorization.

	   The authorization header.
	*/
	TpAuthorization string

	/* TpExpressAcceptorID.

	   The Express acceptorId. If all three Express credentials are specified in the request headers, triPOS will use these credentials instead of the credentials in the triPOS.config for that request only.
	*/
	TpExpressAcceptorID string

	/* TpExpressAccountID.

	   The Express accountId. If all three Express credentials are specified in the request headers, triPOS will use these credentials instead of the credentials in the triPOS.config for that request only.
	*/
	TpExpressAccountID string

	/* TpExpressAccountToken.

	   The Express accountToken. If all three Express credentials are specified in the request headers, triPOS will use these credentials instead of the credentials in the triPOS.config for that request only.
	*/
	TpExpressAccountToken string

	/* TpRequestID.

	   A unique ID for this request. This value should be a UUID or GUID. <a href='https://triposcert.vantiv.com/api/help/kb/requestid.html'>more&raquo;</a>
	*/
	TpRequestID string

	/* TpReturnLogs.

	   Set to true to have logs populated in the response.
	*/
	TpReturnLogs *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the getv1signature params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Getv1signatureParams) WithDefaults() *Getv1signatureParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the getv1signature params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *Getv1signatureParams) SetDefaults() {
	var (
		contentTypeDefault = string("application/json")
	)

	val := Getv1signatureParams{
		ContentType: contentTypeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the getv1signature params
func (o *Getv1signatureParams) WithTimeout(timeout time.Duration) *Getv1signatureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the getv1signature params
func (o *Getv1signatureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the getv1signature params
func (o *Getv1signatureParams) WithContext(ctx context.Context) *Getv1signatureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the getv1signature params
func (o *Getv1signatureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the getv1signature params
func (o *Getv1signatureParams) WithHTTPClient(client *http.Client) *Getv1signatureParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the getv1signature params
func (o *Getv1signatureParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the getv1signature params
func (o *Getv1signatureParams) WithContentType(contentType string) *Getv1signatureParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the getv1signature params
func (o *Getv1signatureParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithTpApplicationID adds the tpApplicationID to the getv1signature params
func (o *Getv1signatureParams) WithTpApplicationID(tpApplicationID string) *Getv1signatureParams {
	o.SetTpApplicationID(tpApplicationID)
	return o
}

// SetTpApplicationID adds the tpApplicationId to the getv1signature params
func (o *Getv1signatureParams) SetTpApplicationID(tpApplicationID string) {
	o.TpApplicationID = tpApplicationID
}

// WithTpApplicationName adds the tpApplicationName to the getv1signature params
func (o *Getv1signatureParams) WithTpApplicationName(tpApplicationName string) *Getv1signatureParams {
	o.SetTpApplicationName(tpApplicationName)
	return o
}

// SetTpApplicationName adds the tpApplicationName to the getv1signature params
func (o *Getv1signatureParams) SetTpApplicationName(tpApplicationName string) {
	o.TpApplicationName = tpApplicationName
}

// WithTpApplicationVersion adds the tpApplicationVersion to the getv1signature params
func (o *Getv1signatureParams) WithTpApplicationVersion(tpApplicationVersion string) *Getv1signatureParams {
	o.SetTpApplicationVersion(tpApplicationVersion)
	return o
}

// SetTpApplicationVersion adds the tpApplicationVersion to the getv1signature params
func (o *Getv1signatureParams) SetTpApplicationVersion(tpApplicationVersion string) {
	o.TpApplicationVersion = tpApplicationVersion
}

// WithTpAuthorization adds the tpAuthorization to the getv1signature params
func (o *Getv1signatureParams) WithTpAuthorization(tpAuthorization string) *Getv1signatureParams {
	o.SetTpAuthorization(tpAuthorization)
	return o
}

// SetTpAuthorization adds the tpAuthorization to the getv1signature params
func (o *Getv1signatureParams) SetTpAuthorization(tpAuthorization string) {
	o.TpAuthorization = tpAuthorization
}

// WithTpExpressAcceptorID adds the tpExpressAcceptorID to the getv1signature params
func (o *Getv1signatureParams) WithTpExpressAcceptorID(tpExpressAcceptorID string) *Getv1signatureParams {
	o.SetTpExpressAcceptorID(tpExpressAcceptorID)
	return o
}

// SetTpExpressAcceptorID adds the tpExpressAcceptorId to the getv1signature params
func (o *Getv1signatureParams) SetTpExpressAcceptorID(tpExpressAcceptorID string) {
	o.TpExpressAcceptorID = tpExpressAcceptorID
}

// WithTpExpressAccountID adds the tpExpressAccountID to the getv1signature params
func (o *Getv1signatureParams) WithTpExpressAccountID(tpExpressAccountID string) *Getv1signatureParams {
	o.SetTpExpressAccountID(tpExpressAccountID)
	return o
}

// SetTpExpressAccountID adds the tpExpressAccountId to the getv1signature params
func (o *Getv1signatureParams) SetTpExpressAccountID(tpExpressAccountID string) {
	o.TpExpressAccountID = tpExpressAccountID
}

// WithTpExpressAccountToken adds the tpExpressAccountToken to the getv1signature params
func (o *Getv1signatureParams) WithTpExpressAccountToken(tpExpressAccountToken string) *Getv1signatureParams {
	o.SetTpExpressAccountToken(tpExpressAccountToken)
	return o
}

// SetTpExpressAccountToken adds the tpExpressAccountToken to the getv1signature params
func (o *Getv1signatureParams) SetTpExpressAccountToken(tpExpressAccountToken string) {
	o.TpExpressAccountToken = tpExpressAccountToken
}

// WithTpRequestID adds the tpRequestID to the getv1signature params
func (o *Getv1signatureParams) WithTpRequestID(tpRequestID string) *Getv1signatureParams {
	o.SetTpRequestID(tpRequestID)
	return o
}

// SetTpRequestID adds the tpRequestId to the getv1signature params
func (o *Getv1signatureParams) SetTpRequestID(tpRequestID string) {
	o.TpRequestID = tpRequestID
}

// WithTpReturnLogs adds the tpReturnLogs to the getv1signature params
func (o *Getv1signatureParams) WithTpReturnLogs(tpReturnLogs *bool) *Getv1signatureParams {
	o.SetTpReturnLogs(tpReturnLogs)
	return o
}

// SetTpReturnLogs adds the tpReturnLogs to the getv1signature params
func (o *Getv1signatureParams) SetTpReturnLogs(tpReturnLogs *bool) {
	o.TpReturnLogs = tpReturnLogs
}

// WriteToRequest writes these params to a swagger request
func (o *Getv1signatureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}

	// header param tp-application-id
	if err := r.SetHeaderParam("tp-application-id", o.TpApplicationID); err != nil {
		return err
	}

	// header param tp-application-name
	if err := r.SetHeaderParam("tp-application-name", o.TpApplicationName); err != nil {
		return err
	}

	// header param tp-application-version
	if err := r.SetHeaderParam("tp-application-version", o.TpApplicationVersion); err != nil {
		return err
	}

	// header param tp-authorization
	if err := r.SetHeaderParam("tp-authorization", o.TpAuthorization); err != nil {
		return err
	}

	// header param tp-express-acceptor-id
	if err := r.SetHeaderParam("tp-express-acceptor-id", o.TpExpressAcceptorID); err != nil {
		return err
	}

	// header param tp-express-account-id
	if err := r.SetHeaderParam("tp-express-account-id", o.TpExpressAccountID); err != nil {
		return err
	}

	// header param tp-express-account-token
	if err := r.SetHeaderParam("tp-express-account-token", o.TpExpressAccountToken); err != nil {
		return err
	}

	// header param tp-request-id
	if err := r.SetHeaderParam("tp-request-id", o.TpRequestID); err != nil {
		return err
	}

	if o.TpReturnLogs != nil {

		// header param tp-return-logs
		if err := r.SetHeaderParam("tp-return-logs", swag.FormatBool(*o.TpReturnLogs)); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
