// Code generated by go-swagger; DO NOT EDIT.

package lanes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/thermeon/boilerplate-golang/infrastructures/clients/triposlane/models"
)

// NewLanesPostParams creates a new LanesPostParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLanesPostParams() *LanesPostParams {
	return &LanesPostParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLanesPostParamsWithTimeout creates a new LanesPostParams object
// with the ability to set a timeout on a request.
func NewLanesPostParamsWithTimeout(timeout time.Duration) *LanesPostParams {
	return &LanesPostParams{
		timeout: timeout,
	}
}

// NewLanesPostParamsWithContext creates a new LanesPostParams object
// with the ability to set a context for a request.
func NewLanesPostParamsWithContext(ctx context.Context) *LanesPostParams {
	return &LanesPostParams{
		Context: ctx,
	}
}

// NewLanesPostParamsWithHTTPClient creates a new LanesPostParams object
// with the ability to set a custom HTTPClient for a request.
func NewLanesPostParamsWithHTTPClient(client *http.Client) *LanesPostParams {
	return &LanesPostParams{
		HTTPClient: client,
	}
}

/* LanesPostParams contains all the parameters to send to the API endpoint
   for the lanes post operation.

   Typically these are written to a http.Request.
*/
type LanesPostParams struct {

	/* ContentType.

	   Content type for request.

	   Default: "application/json"
	*/
	ContentType string

	/* Request.

	   The lane information
	*/
	Request *models.LaneRequest

	/* TpApplicationID.

	   The ID of the business application.
	*/
	TpApplicationID string

	/* TpApplicationName.

	   The name of the business application.
	*/
	TpApplicationName string

	/* TpApplicationVersion.

	   The version of the business application.
	*/
	TpApplicationVersion string

	/* TpExpressAcceptorID.

	   The Express acceptorId.
	*/
	TpExpressAcceptorID string

	/* TpExpressAccountID.

	   The Express accountId.
	*/
	TpExpressAccountID string

	/* TpExpressAccountToken.

	   The Express accountToken.
	*/
	TpExpressAccountToken string

	/* TpRequestID.

	   A unique ID for this request. This value should be a UUID or GUID.
	*/
	TpRequestID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the lanes post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LanesPostParams) WithDefaults() *LanesPostParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the lanes post params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LanesPostParams) SetDefaults() {
	var (
		contentTypeDefault = string("application/json")
	)

	val := LanesPostParams{
		ContentType: contentTypeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the lanes post params
func (o *LanesPostParams) WithTimeout(timeout time.Duration) *LanesPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lanes post params
func (o *LanesPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lanes post params
func (o *LanesPostParams) WithContext(ctx context.Context) *LanesPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lanes post params
func (o *LanesPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lanes post params
func (o *LanesPostParams) WithHTTPClient(client *http.Client) *LanesPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lanes post params
func (o *LanesPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentType adds the contentType to the lanes post params
func (o *LanesPostParams) WithContentType(contentType string) *LanesPostParams {
	o.SetContentType(contentType)
	return o
}

// SetContentType adds the contentType to the lanes post params
func (o *LanesPostParams) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithRequest adds the request to the lanes post params
func (o *LanesPostParams) WithRequest(request *models.LaneRequest) *LanesPostParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the lanes post params
func (o *LanesPostParams) SetRequest(request *models.LaneRequest) {
	o.Request = request
}

// WithTpApplicationID adds the tpApplicationID to the lanes post params
func (o *LanesPostParams) WithTpApplicationID(tpApplicationID string) *LanesPostParams {
	o.SetTpApplicationID(tpApplicationID)
	return o
}

// SetTpApplicationID adds the tpApplicationId to the lanes post params
func (o *LanesPostParams) SetTpApplicationID(tpApplicationID string) {
	o.TpApplicationID = tpApplicationID
}

// WithTpApplicationName adds the tpApplicationName to the lanes post params
func (o *LanesPostParams) WithTpApplicationName(tpApplicationName string) *LanesPostParams {
	o.SetTpApplicationName(tpApplicationName)
	return o
}

// SetTpApplicationName adds the tpApplicationName to the lanes post params
func (o *LanesPostParams) SetTpApplicationName(tpApplicationName string) {
	o.TpApplicationName = tpApplicationName
}

// WithTpApplicationVersion adds the tpApplicationVersion to the lanes post params
func (o *LanesPostParams) WithTpApplicationVersion(tpApplicationVersion string) *LanesPostParams {
	o.SetTpApplicationVersion(tpApplicationVersion)
	return o
}

// SetTpApplicationVersion adds the tpApplicationVersion to the lanes post params
func (o *LanesPostParams) SetTpApplicationVersion(tpApplicationVersion string) {
	o.TpApplicationVersion = tpApplicationVersion
}

// WithTpExpressAcceptorID adds the tpExpressAcceptorID to the lanes post params
func (o *LanesPostParams) WithTpExpressAcceptorID(tpExpressAcceptorID string) *LanesPostParams {
	o.SetTpExpressAcceptorID(tpExpressAcceptorID)
	return o
}

// SetTpExpressAcceptorID adds the tpExpressAcceptorId to the lanes post params
func (o *LanesPostParams) SetTpExpressAcceptorID(tpExpressAcceptorID string) {
	o.TpExpressAcceptorID = tpExpressAcceptorID
}

// WithTpExpressAccountID adds the tpExpressAccountID to the lanes post params
func (o *LanesPostParams) WithTpExpressAccountID(tpExpressAccountID string) *LanesPostParams {
	o.SetTpExpressAccountID(tpExpressAccountID)
	return o
}

// SetTpExpressAccountID adds the tpExpressAccountId to the lanes post params
func (o *LanesPostParams) SetTpExpressAccountID(tpExpressAccountID string) {
	o.TpExpressAccountID = tpExpressAccountID
}

// WithTpExpressAccountToken adds the tpExpressAccountToken to the lanes post params
func (o *LanesPostParams) WithTpExpressAccountToken(tpExpressAccountToken string) *LanesPostParams {
	o.SetTpExpressAccountToken(tpExpressAccountToken)
	return o
}

// SetTpExpressAccountToken adds the tpExpressAccountToken to the lanes post params
func (o *LanesPostParams) SetTpExpressAccountToken(tpExpressAccountToken string) {
	o.TpExpressAccountToken = tpExpressAccountToken
}

// WithTpRequestID adds the tpRequestID to the lanes post params
func (o *LanesPostParams) WithTpRequestID(tpRequestID string) *LanesPostParams {
	o.SetTpRequestID(tpRequestID)
	return o
}

// SetTpRequestID adds the tpRequestId to the lanes post params
func (o *LanesPostParams) SetTpRequestID(tpRequestID string) {
	o.TpRequestID = tpRequestID
}

// WriteToRequest writes these params to a swagger request
func (o *LanesPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Content-Type
	if err := r.SetHeaderParam("Content-Type", o.ContentType); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// header param tp-application-id
	if err := r.SetHeaderParam("tp-application-id", o.TpApplicationID); err != nil {
		return err
	}

	// header param tp-application-name
	if err := r.SetHeaderParam("tp-application-name", o.TpApplicationName); err != nil {
		return err
	}

	// header param tp-application-version
	if err := r.SetHeaderParam("tp-application-version", o.TpApplicationVersion); err != nil {
		return err
	}

	// header param tp-express-acceptor-id
	if err := r.SetHeaderParam("tp-express-acceptor-id", o.TpExpressAcceptorID); err != nil {
		return err
	}

	// header param tp-express-account-id
	if err := r.SetHeaderParam("tp-express-account-id", o.TpExpressAccountID); err != nil {
		return err
	}

	// header param tp-express-account-token
	if err := r.SetHeaderParam("tp-express-account-token", o.TpExpressAccountToken); err != nil {
		return err
	}

	// header param tp-request-id
	if err := r.SetHeaderParam("tp-request-id", o.TpRequestID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
