// Code generated by go-swagger; DO NOT EDIT.

package refund

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/thermeon/boilerplate-golang/infrastructures/clients/tripos/models"
)

// Postv1refundReader is a Reader for the Postv1refund structure.
type Postv1refundReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *Postv1refundReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostv1refundOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostv1refundUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostv1refundOK creates a Postv1refundOK with default headers values
func NewPostv1refundOK() *Postv1refundOK {
	return &Postv1refundOK{}
}

/* Postv1refundOK describes a response with status code 200, with default header values.

Success
*/
type Postv1refundOK struct {
	Payload *models.RefundResponse
}

func (o *Postv1refundOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/refund][%d] postv1refundOK  %+v", 200, o.Payload)
}
func (o *Postv1refundOK) GetPayload() *models.RefundResponse {
	return o.Payload
}

func (o *Postv1refundOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RefundResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostv1refundUnauthorized creates a Postv1refundUnauthorized with default headers values
func NewPostv1refundUnauthorized() *Postv1refundUnauthorized {
	return &Postv1refundUnauthorized{}
}

/* Postv1refundUnauthorized describes a response with status code 401, with default header values.

Returned if the AcceptorId, AccountId, AccountToken and TerminalId (config file only) are not provided in the HTTP request header or in the config file.
*/
type Postv1refundUnauthorized struct {
}

func (o *Postv1refundUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v1/refund][%d] postv1refundUnauthorized ", 401)
}

func (o *Postv1refundUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
